FROM centos:7

LABEL version=1.0
LABEL description="This is an apache image"
LABEL vendor=me

RUN yum install httpd -y

# WORKDIR /var/www/html

COPY blog /var/www/html/prueba.html

RUN echo "$(whoami)" >  /var/www/html/user1.html

RUN useradd ricardo

#RUN chown ricardo /var/www/html

USER ricardo

RUN echo "$(whoami)" >  /tmp/user2.html
#ENV contenido prueba

#VOLUME /var/www/html 

#RUN echo "$contenido" > /var/www/html/prueba.html

#EXPOSE 8080

USER root

RUN cp /tmp/user2.html /var/www/html/user2.html

COPY run.sh /run.sh

CMD sh /run.sh

#CMD apachectl -DFOREGROUND
